name: Deploy to production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    # https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'v1.33.1'
      id: install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::906109891612:role/gh-actions-role
        aws-region: sa-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Load secrets and save to app.env
      run: aws secretsmanager get-secret-value --secret-id simple_bank --query SecretString --output text | jq -r 'to_entries | map("\(.key)=\(.value)") | .[]' > app.env

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: simplebank
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push -a $ECR_REGISTRY/$ECR_REPOSITORY

    - name: Update kube config
      run: aws eks update-kubeconfig --name simple-bank --region sa-east-1

    - name: Deploy image to Amazon EKS
      run: |
        kubectl apply -f eks/aws-auth.yml
        kubectl apply -f eks/deployment.yml
        kubectl apply -f eks/service.yml
        kubectl apply -f eks/issuer.yml
        kubectl apply -f eks/ingress-nginx.yml
        kubectl apply -f eks/ingres.yml